Updated README
ibm-bluemix-mobile-services/bms-clientsdk-android-core pull request #44
Opened 2017-04-27 21:50 UTC by AnthonyOliveri

- Added lots of content, including thorough usage examples
- Used the same format as Swift [BMSCore](https://github.com/ibm-bluemix-mobile-services/bms-clientsdk-swift-core)

2017-05-01 14:19 UTC, dgonz7 requested changes
Aside from those two minor changes I noted, everything else is fine.

2017-05-01 14:19 UTC, dgonz7 commented on README.md
> -[![Maven Central](https://maven-badges.herokuapp.com/maven-central/com.ibm.mobilefirstplatform.clientsdk.android/core/badge.svg)](https://maven-badges.herokuapp.com/maven-central/com.ibm.mobilefirstp
Leave this here, this is standard for all Java github repos.

2017-05-01 14:19 UTC, dgonz7 commented on README.md
> -[![javadoc.io](https://javadoc-emblem.rhcloud.com/doc/com.ibm.mobilefirstplatform.clientsdk.android/core/badge.svg)](http://www.javadoc.io/doc/com.ibm.mobilefirstplatform.clientsdk.android/core)
Leave this here, it is the only direct link to the Javadoc.

2017-05-01 15:22 UTC, AnthonyOliveri commented on README.md
> -[![Maven Central](https://maven-badges.herokuapp.com/maven-central/com.ibm.mobilefirstplatform.clientsdk.android/core/badge.svg)](https://maven-badges.herokuapp.com/maven-central/com.ibm.mobilefirstp
Are you referring to the Build Status, or Maven Central badge? The Maven Central badge is still there, just moved to a different spot. I think it's confusing to have 2 badges for Build Status, especially when one is passing and one is failing. Most Github repos have just one build status.

2017-05-01 15:23 UTC, AnthonyOliveri commented on README.md
> -[![javadoc.io](https://javadoc-emblem.rhcloud.com/doc/com.ibm.mobilefirstplatform.clientsdk.android/core/badge.svg)](http://www.javadoc.io/doc/com.ibm.mobilefirstplatform.clientsdk.android/core)
I added another link to the Javadoc in the Example Usage section. Do you still want to keep this Javadoc badge?

2017-05-01 15:27 UTC, AnthonyOliveri commented on README.md
> -[![Maven Central](https://maven-badges.herokuapp.com/maven-central/com.ibm.mobilefirstplatform.clientsdk.android/core/badge.svg)](https://maven-badges.herokuapp.com/maven-central/com.ibm.mobilefirstp
Another note: I have another task to update the README badges for all SDKs (Swift, Android, and Cordova) to be consistent. So whatever we decide will need to be done to all other SDKs for all platforms (except for platform-dependent badges like Maven Central, of course).

2017-05-03 22:23 UTC, dgonz7 commented on README.md
> -[![Maven Central](https://maven-badges.herokuapp.com/maven-central/com.ibm.mobilefirstplatform.clientsdk.android/core/badge.svg)](https://maven-badges.herokuapp.com/maven-central/com.ibm.mobilefirstp
Yup, meant Maven Central one, didn't see you moved it.

2017-05-03 22:28 UTC, dgonz7 commented on README.md
> -[![javadoc.io](https://javadoc-emblem.rhcloud.com/doc/com.ibm.mobilefirstplatform.clientsdk.android/core/badge.svg)](http://www.javadoc.io/doc/com.ibm.mobilefirstplatform.clientsdk.android/core)
Nope that's fine, as long as it's somewhere.

2017-05-03 22:30 UTC, dgonz7 approved these changes

2017-05-03 22:30 UTC, merged