Added new region constant for Germany
ibm-bluemix-mobile-services/bms-clientsdk-android-core pull request #46
Opened 2017-07-19 16:48 UTC by parvathy-u

2017-07-20 19:50 UTC, AnthonyOliveri requested changes

2017-07-20 19:50 UTC, AnthonyOliveri commented on lib/src/main/java/com/ibm/mobilefirstplatform/clientsdk/android/core/api/BMSClient.java
> +    public final static String REGION_GERMANY = ".eu-de.bluemix.net";
This should be aligned with the lines above

2017-07-21 05:47 UTC, parvathy-u commented
Alignment is updated.

2017-07-21 15:56 UTC, AnthonyOliveri approved these changes

2017-07-21 16:01 UTC, merged